# Generated by Django 4.1.13 on 2024-03-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_todo_todo_headlines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='headlines',
            new_name='todo',
        ),
    ]
