# Generated by Django 4.1.13 on 2024-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('', 'Select'), ('progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='', max_length=50),
        ),
    ]
